### ISSUE TITLE
Fan Network issue Uninferred width for target below

### ISSUE THREAD

**Issue by masfiyan** [merledu/magma-si#15]
@syedowaisalishah please check the error in FanNetworkcom

**Comment by masfiyan** [comment]
please check the error in PR #16 
`[info] FanNetcomTester:
[info] - FanNetcomplete Test *** FAILED ***
[info]   firrtl.passes.PassExceptions: firrtl.passes.CheckWidths$UninferredWidth:  : Uninferred width for target below. (Did you forget to assign to it?)
[info]     circuit FanNetworkcom:
[info]     └── module FanNetworkcom:
[info]         └── io.i_add_en_bus
[info] firrtl.passes.CheckWidths$UninferredWidth:  : Uninferred width for target below. (Did you forget to assign to it?)
[info]     circuit FanNetworkcom:
[info]     └── module FanNetworkcom:
[info]         └── io.i_sel_bus
[info] firrtl.passes.PassException: 2 errors detected!
[info]   ...
[info] Run completed in 5 seconds, 527 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error]         magmasi.components.FanNetcomTester
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful`

**Comment by syedowaisalishah** [comment]
Done check new branch i resolve that error....!
